import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica', fontSize: 10, color: '#334155' },
  header: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 40, borderBottomWidth: 1, borderBottomColor: '#E2E8F0', paddingBottom: 20 },
  title: { fontSize: 24, fontWeight: 'bold', color: '#0F172A', marginBottom: 4 },
  companyName: { fontSize: 16, fontWeight: 'bold', color: '#0F172A', marginBottom: 4 },
  text: { marginBottom: 4, lineHeight: 1.4 },
  boldText: { fontWeight: 'bold', color: '#0F172A' },
  section: { marginBottom: 30 },
  tableHeader: { flexDirection: 'row', backgroundColor: '#F8FAFC', padding: 8, borderBottomWidth: 1, borderBottomColor: '#E2E8F0', fontWeight: 'bold', color: '#0F172A' },
  tableRow: { flexDirection: 'row', padding: 8, borderBottomWidth: 1, borderBottomColor: '#F1F5F9' },
  col1: { flex: 3 },
  col2: { flex: 1, textAlign: 'center' },
  col3: { flex: 1, textAlign: 'right' },
  summaryContainer: { width: '40%', alignSelf: 'flex-end', marginTop: 20 },
  summaryRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 4 },
  totalRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 8, borderTopWidth: 1, borderTopColor: '#E2E8F0', marginTop: 4, fontWeight: 'bold' },
  footer: { position: 'absolute', bottom: 40, left: 40, right: 40, textAlign: 'center', color: '#94A3B8', fontSize: 9, borderTopWidth: 1, borderTopColor: '#E2E8F0', paddingTop: 10 }
});

export const MinimalModernTemplate = ({ invoice }) => {
  const sym = invoice.currencySymbol || '$'; // Catch the dynamic symbol!

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        
        <View style={styles.header}>
          <View>
            <Text style={styles.title}>INVOICE</Text>
            <Text style={styles.text}>Invoice #: {invoice.invoiceNumber}</Text>
            <Text style={styles.text}>Date: {new Date().toLocaleDateString()}</Text>
          </View>
          <View style={{ textAlign: 'right' }}>
            <Text style={styles.companyName}>{invoice.company?.companyName || 'Your Company'}</Text>
            <Text style={styles.text}>{invoice.company?.name || 'Your Name'}</Text>
            <Text style={styles.text}>{invoice.company?.address || ''}</Text>
            {invoice.company?.gstNumber ? <Text style={styles.text}>Tax ID: {invoice.company.gstNumber}</Text> : null}
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.boldText}>Billed To:</Text>
          <Text style={styles.text}>{invoice.client?.name || 'Client Name'}</Text>
          <Text style={styles.text}>{invoice.client?.email || ''}</Text>
          <Text style={styles.text}>{invoice.client?.address || ''}</Text>
        </View>

        <View style={styles.section}>
          <View style={styles.tableHeader}>
            <Text style={styles.col1}>Description</Text>
            <Text style={styles.col2}>Qty</Text>
            <Text style={styles.col3}>Price</Text>
            <Text style={styles.col3}>Amount</Text>
          </View>
          {invoice.items.map((item, i) => (
            <View key={i} style={styles.tableRow}>
              <Text style={styles.col1}>{item.name}</Text>
              <Text style={styles.col2}>{item.quantity}</Text>
              <Text style={styles.col3}>{sym}{item.price.toFixed(2)}</Text>
              <Text style={styles.col3}>{sym}{(item.quantity * item.price).toFixed(2)}</Text>
            </View>
          ))}
        </View>

        <View style={styles.summaryContainer}>
          <View style={styles.summaryRow}>
            <Text style={styles.text}>Subtotal:</Text>
            <Text style={styles.text}>{sym}{invoice.subtotal?.toFixed(2)}</Text>
          </View>
          {invoice.discount > 0 && (
            <View style={styles.summaryRow}>
              <Text style={styles.text}>Discount:</Text>
              <Text style={styles.text}>-{sym}{invoice.discount?.toFixed(2)}</Text>
            </View>
          )}
          <View style={styles.summaryRow}>
            <Text style={styles.text}>Tax ({invoice.taxRate}%):</Text>
            <Text style={styles.text}>{sym}{invoice.taxTotal?.toFixed(2)}</Text>
          </View>
          <View style={styles.totalRow}>
            <Text style={styles.boldText}>Total Due:</Text>
            <Text style={styles.boldText}>{sym}{invoice.total?.toFixed(2)}</Text>
          </View>
        </View>

        {invoice.notes && (
          <View style={{ marginTop: 40 }}>
            <Text style={styles.boldText}>Notes & Terms:</Text>
            <Text style={styles.text}>{invoice.notes}</Text>
          </View>
        )}

        <Text style={styles.footer}>Thank you for your business. Generated by SaaS Invoice.</Text>
      </Page>
    </Document>
  );
};